### ISSUE TITLE
Status: telega-server: aborted (core dumped) | Error after installing telega.el from GUIX on fresh Mint install.

### ISSUE THREAD

**Issue by digitables** [zevlg/telega.el#276] opened 2021-03-06 22:28 UTC
Status: telega-server: aborted (core dumped) | Error after installing telega.el from GUIX on fresh Mint install.

## Telega Setup
*OS*: Linux Mint 20.1
*Emacs*: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
*Telega*: telega v0.7.1 (TDLib v1.7.0) (telega-server v0.7.0)

## Current Behavior
See Appendix A for log file snippet. The crash occurs when a sticker set fails to parse. I cannot use telega.el at all during this period.

## Steps to Reproduce

1. On a fresh GUIX install, install emacs-telega. I was working with an emacs that was entirely installed in GUIX, when previously I used Straight.el.
2. Invoke (guix-emacs-autoload-packages) to load all packages installed though GUIX
3. Configure telega.el through the following snippet:
```
(use-package telega
  :commands (telega) :defer t
  :config
  (setq telega-completing-read-function #'ivy-completing-read)

  (add-hook 'telega-root-mode-hook
            'my/visual-fill-column-mode)
  (add-hook 'telega-chat-mode-hook
            'my/visual-fill-column-mode)
  (add-hook 'telega-chat-mode-hook
            'my/visual-fill-column-mode))
```
4. Launch telega through `(telega)`. The program should fail at this point, with the log in accordance with Appendix A

## Appendix A: Telega Server Log at point of failure
```
[ 3][t 3][1615067703.112044572][NetQuery.h:244][#1][!Session:4:main][&net_query]	[Query:[id:1048576][tl:0x2619a90e][state:Query]] [state:Session: pending]
[ 3][t 3][1615067703.112049579][NetQuery.h:244][#1][!Session:4:main][&net_query]	[Query:[id:1048576][tl:0x2619a90e][state:Query]] [state:Session: trying to send to mtproto::connection]
[ 3][t 3][1615067703.112051486][Session.cpp:964][#1][!Session:4:main][&net_query]	Send query to connection [Query:[id:1048576][tl:0x2619a90e][state:Query]] [msg_id:0x6043fa36bb7d23e4][invoke_after:0x0000000000000000]
[ 3][t 3][1615067703.112055301][StickersManager.cpp:3380][#1][!StickersManager]	Successfully loaded sticker set 1650187153075863553 without stickers of size 2616 from database
[ 3][t 3][1615067703.112060546][StickersManager.cpp:3065][#1][!StickersManager]	Update sticker set 1650187153075863553: installed = true, archived = false, changed = false, from_database = true
[ 0][t 3][1615067703.131536245][StickersManager.cpp:3398][#1][!StickersManager]	Failed to parse sticker set 1650187153075863553: [Error : 0 : Invalid flags 20 left, current bit is 4 at 68]
0000001e 00001489 00000001 16e6a479 7d9fabe6 a8bb45a2 742f7213 20616172 63697473 2072656b 6b636170 72747205 00006161 0000006e b2de775e 00000005
00000014 989ff004 00000094 01ac0200 00000000 00000000 00000000 00000000 00000000 0000006d 006b0080 00001706 00000004 00000000 02000000 00000001
2b600015 9ce33fc7 fb047b1f 9e29a848 405fdd09 0000b044 00000001 16e6a479 a79db010 a5463685 2ff6dba9 00000000 00000001 00000000 0000006d 000056ff
00001706 34303814 32373037 325f3134 31373232 6265772e 00000070 00000000 00000000 00000000 00000004 00000000 02000008 00000001 2b600015 9ce33fc7
fb047b1f 9e29a848 405fdd09 0000b044 00000001 16e6a479 a79db010 a5463685 00009946 35363118 37383130 30333531 36383537 33353533 6265772e 00000070
00000000 00000000 000107fe 02b3071b 494c5fdc 084b9200 44444580 4352484d 475b7e44 48447603 875a8851 45724247 55464d74
```

**Comment by zevlg** [comment] 2021-03-07 13:06
I'm closing this.  Caused by running older TDLib on newer TDLib database

**Closed by zevlg** 2021-03-07 13:06 UTC
