### ISSUE TITLE
td/telegram/td_json_client.h: No such file or directory

### ISSUE THREAD

**Issue by Andrmist** [zevlg/telega.el#188] opened 2020-07-10 15:09 UTC
<pre>make[1]: Entering directory &apos;/home/master/telega-server/server&apos;
c++ -I/usr/local/include -Wall -g -pthread -std=c++11 -DWITH_VOIP -DTGVOIP_NO_STDOUT_LOGS -o telega-server telega-server.c telega-dat.c telega-pngext.c telega-voip.cpp -L/usr/local/lib -Wl,-rpath,/usr/local/lib -ltdjson -ltgvoip
<b>telega-server.c:10:10:</b> <font color="#EF2929"><b>fatal error: </b></font>td/telegram/td_json_client.h: No such file or directory
 #include <font color="#EF2929"><b>&lt;td/telegram/td_json_client.h&gt;</b></font>
          <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
compilation terminated.
Makefile:30: recipe for target &apos;telega-server&apos; failed
make[1]: *** [telega-server] Error 1
make[1]: Leaving directory &apos;/home/master/telega-server/server&apos;
Makefile:6: recipe for target &apos;telega-server&apos; failed
make: *** [telega-server] Error 2</pre>

## Telega Setup
*OS*: Linux jetson1 4.9.140-tegra #1 SMP PREEMPT Tue Apr 28 14:06:23 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
*Emacs*: GNU Emacs 26.3 (build 2, aarch64-unknown-linux-gnu, GTK+ Version 3.22.30) of 2019-09-17
user-error: Minibuffer window is not active 
*Telega*: can't provide because server not builded 

I install telega from MELPA. Also tried to install from git.

## Current Behavior

It crashes when i want to build telega-server

## Steps to Reproduce

1. install telega from melpa or git
2. run M-x telega
3. select y when asked "Build 'telega-server'?"

**Comment by zevlg** [comment] 2020-07-10 18:13
This is TDLib related issue, or tdlib package is broken on you system. There was similar problems caused by broken tdlib package in Fedora

Try installing TDLib by hand.  Also take into account that telega.el master is TDLib 1.6.6 only

**Comment by brettgilio** [comment] 2020-07-19 04:06
Closing, as the issue seems resolved. Reopen if necessary.

**Closed by brettgilio** 2020-07-19 04:06 UTC

**Comment by jasonmj** [comment] 2021-04-09 13:32
I have this same issue. Using TDLib 1.7.0.

**Comment by zevlg** [comment] 2021-04-09 15:14
> I have this same issue. Using TDLib 1.7.0.

Set `telega-server-libs-prefix` to the prefix, where your TDLib files are installed before running `M-x telega RET`

TDLib installation is required before running telega, just compiling it is not enough.  Don't forget to run `$ sudo make install` step from https://zevlg.github.io/telega.el/#building-tdlib

**Comment by jasonmj** [comment] 2021-04-09 16:26
Awesome, thank you! That got me past my block. I'm on NixOS, so I needed to provide a full path to TDLib.
