### ISSUE TITLE
telega-server fails to load shared libraries on start

### ISSUE THREAD

**Issue by evan3334** [zevlg/telega.el#191] opened 2020-07-21 19:44 UTC
## Telega Setup
*OS*: Ubuntu 19.10
*Emacs*: 26.3 (x86_64-pc-linux-gnu)
*Telega*: telega v0.6.27-2.5c39c3a (from GNU Guix)

## Current Behavior
When starting Telega, I get a warning that says `installed telega-server version 0.0.0 [unknown]<0.6.1, rebuild? (y or n)`. If I press "y," it says 
```
make: *** No rule to make target 'server-reinstall'.  Stop.
telega-server-build: ‘telega-server’ installation failed
```
Upon pressing "n", I get the following message in the Telega root buffer: 
```
Status: telega-server: exited abnormally with code 127
/home/evan/.guix-profile/bin/telega-server: error while loading shared libraries: libopus.so.0: cannot open shared object file: No such file or directory
```

## Steps to Reproduce
1. Install `emacs` and `emacs-telega` from GNU Guix, revision `d4b02a6`.
2. Open Emacs and run `M-x telega RET`.
3. Press either "y" or "n" when prompted about rebuilding the server. Behavior described above should occur.

## Possible Solution
It may be some kind of error with how `telega-server` from Guix is linked? I don't know. The output of `ldd $(which telega-server)` is as follows:
```
  linux-vdso.so.1 (0x00007fff42f4a000)
  libtdjson.so.1.6.6 => /gnu/store/zxm3fz4jd3h9hbmfipzpmz32h5ak4brx-tdlib-1.6.6-0.f45d80f/lib/libtdjson.so.1.6.6 (0x00007f25d7863000)
  libtgvoip.so.0 => /usr/local/lib/libtgvoip.so.0 (0x00007f25d768f000)
  libstdc++.so.6 => /gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/libstdc++.so.6 (0x00007f25d7504000)
  libm.so.6 => /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libm.so.6 (0x00007f25d73c3000)
  libgcc_s.so.1 => /gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/libgcc_s.so.1 (0x00007f25d73aa000)
  libpthread.so.0 => /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libpthread.so.0 (0x00007f25d7387000)
  libc.so.6 => /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libc.so.6 (0x00007f25d71ca000)
  libssl.so.1.1 => /gnu/store/hcxpkksmbql6s4al8yy2myr25kh4cic0-openssl-1.1.1g/lib/libssl.so.1.1 (0x00007f25d7133000)
  libcrypto.so.1.1 => /gnu/store/hcxpkksmbql6s4al8yy2myr25kh4cic0-openssl-1.1.1g/lib/libcrypto.so.1.1 (0x00007f25d6e3b000)
  libdl.so.2 => /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libdl.so.2 (0x00007f25d6e36000)
  libz.so.1 => /gnu/store/rykm237xkmq7rl1p0nwass01p090p88x-zlib-1.2.11/lib/libz.so.1 (0x00007f25d6e14000)
  /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2 (0x00007f25d875a000)
  libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f25d6d89000)
```
All libraries except libopus are linked to some path in the Guix store.

Please let me know if there's any missing information I should provide.

**Comment by brettgilio** [comment] 2020-07-21 21:46
This issue has been identified to be caused by libtgvoip attempting to link opus. As libtgvoip is not currently functional in telega.el this functionality has been disabled in Guix to preserve the linkage issue. The linkage issue will be investigated further if/when VOIP support for telega.el becomes apparent.

http://git.savannah.gnu.org/cgit/guix.git/commit/?id=d2e0b16c48a7f7b5ba0501c1988988a962fe147c

Closing.

**Closed by brettgilio** 2020-07-21 21:46 UTC
Labels: WIP, bug, guix
