### ISSUE TITLE
Include tdlib in the repo as a submodule?

### ISSUE THREAD

**Issue by cireu** [zevlg/telega.el#68] opened 2019-07-22 10:50 UTC
I think it will be more easy for developing and installation.

**Comment by zevlg** [comment] 2019-07-23 14:45
Yeah, you are right. Will eliminate invalid tdlib version problem

**Comment by mrkiko** [comment] 2019-07-29 06:03
I personally don't think bundling libraries is good in general, at least when we can avoid doing so.
And tdlib is by no mean a small library.

**Comment by zevlg** [comment] 2019-07-29 06:43
> I personally don't think bundling libraries is good in general, at least when we can avoid doing so.
> And tdlib is by no mean a small library.

Including TDLib as submodule won't require building it or even checking it out.  The problem is that master branch in `telega.el` is not always synced with TDLib's master branch.  Including submodule might help.

Another (better?) way is just to add test for TDLib version in `$ make test`

**Comment by cireu** [comment] 2019-07-29 12:46
@mrkiko  If you clone a repo without `--recurse-submodules` (default option), Submodules won't be checked out.

You need to do it manually by using

```
git submodule init
git submodule update
```

**Comment by mrkiko** [comment] 2019-07-29 13:34
thanks!
I was meaning - I don't think it's a good idea in general.
I prefer the 2test the version"  solution... more maintenable.
But ... just an opinion.
thank guys!

**Comment by brettgilio** [comment] 2020-01-04 09:22
I also think this should exist as a test case. In fact, I thought it already was. But perhaps I am wrong. :)

**Comment by brettgilio** [comment] 2020-12-16 00:10
I think the development strategy we are adopting post-1.7.0 of tdlib (to keep master consistent with tdlib tagged releases) and only non-master branches can move forward with untagged tdlib invalidates this issue. Closing.

**Closed by brettgilio** 2020-12-16 00:10 UTC
